### ISSUE TITLE
Review for problem statement

### ISSUE THREAD

**Issue by MaXiaoye** [MaXiaoye/cas741#1]
Dear Dr.Smiths,

Please review my problem statement.
Thanks !

Best Regards,
Marshall

@smiths

**Comment by smiths** [comment]
Hello @MaXiaoye.  In the future, please make the reviewer's job even easier and include an explicit link to your document in the issue.  You can copy urls directly into the issues, like:

https://github.com/MaXiaoye/cas741/blob/master/BlankProjectTemplate/Doc/ProblemStatement/ProblemStatement.pdf

Your problem statement is a good start.  However, I'm not really sure what exactly you mean by a breaking effect.  Are you going to try to model the failure of a material so that it breaks at physically meaningful points, or is there some other approach for deciding how the material breaks?  I don't want details, but I want to have a sense of how ambitious you are being with this project.  Is there a link to any similar projects?

**Comment by MaXiaoye** [comment]
Dear Dr.Smiths,

Yes I will pay attention to this and include the link to my document issue. Thank you for the hint !

And yes I am going to try to model a material breaking at physically meaningful points. The model should be like this: a wall is crushed due to a bomb exploding and fragments scatter around. 
I believe there are some similar demos on youtube. Such as https://www.youtube.com/watch?v=y4QptUI-Pxs     I would like to write codes myself to simulate and control performance of fragment scattering. While plug-in can be measurements to be compared with when testing.

Best Regards,
Marshall

@smiths https://www.youtube.com/watch?v=y4QptUI-Pxs

**Comment by smiths** [comment]
Thank you for the additional information.  The video in particular is quite helpful.  In the video the shape's are breaking at the boundary's between the faces.  This isn't the same as simulating where something will break based on physics.  I think what you are saying is that you are going to decide in advance where the cleave planes are and then the different pieces will interact with the momentum provided by the breaking force.  Is that correct?

**Comment by MaXiaoye** [comment]
Dear Dr.Smiths,

Sorry for the late response ! I missed the message yesterday.
Yes exactly !  I am going to try to control the speed and force as input, and pieces movement is output.
I update the first question in my PS based on our talk.  Thank you very much for your review !
https://github.com/MaXiaoye/cas741/blob/master/BlankProjectTemplate/Doc/ProblemStatement/ProblemStatement.pdf

What problem are you trying to solve?

This project tries to implement breaking effect in codes for 3-D models in video games without help from any plug-in. Including different shapes 3-D objects breaking based on physics and pieces interact with the momentum provided by the breaking force. The breaking effect program simulates 3-D objects’ destruction process in vision by implementing scientific computing functions. Users decide speed and force as input while pieces movement is the output after computing.

Best Regards,
Marshall

@smiths

**Comment by smiths** [comment]
Yes, the new version is getting closer.  However, it sounds like your goal is visualization, which implies a gui.  I think you should emphasize the calculations and say that a separate application can be used for visualization.
