### ISSUE TITLE
SRS:  Problem with conservation of energy property of correct solution

### ISSUE THREAD

**Issue by palmerst** [MaXiaoye/cas741#13]
You state that "A correct solution must exhibit the principle of motion as well as conservation of energy."  You include friction for non-airborn fragments, however, which is the conversion of kinetic energy to heat.  You don't track temperature/thermal energy, so your solution won't be able to be checked against the conservation of energy.

**Comment by MaXiaoye** [comment]
Hi Steven,

Friction considered in this project is kinetic friction on the ground while air friction is ignored.
Yes you are correct that I don't track temperature/thermal energy but I actually consider this. 
On the ground where friction existing,  kinetic energy transforms to heat in this project. This is shown and explained in T2 and IM3 that pieces will be stopped because of work done by friction.
In the air we only consider transformation from Ek to Ep.
So totally I think output should exhibit the principle of motion as well as conservation of energy.
 

Best Regards,
Marshall
