### ISSUE TITLE
Review SRS Comments

### ISSUE THREAD

**Issue by smiths** [MaXiaoye/cas741#17]
Please review the comments in the version of your SRS that I pushed in commit number c197680.

**Comment by MaXiaoye** [comment]
Thank you for the detailed comments professor !
I am reviewing and working on modification.

Best Regards,
Marshall

**Comment by smiths** [comment]
No problem Marshall.

**Comment by MaXiaoye** [comment]
Dear professor Smith,

I review your comment carefully and modify my SRS to make it better.
Firstly sorry for my careless such as spelling mistakes.
And actually I believe there are some confusions because of my inaccurate English expression. I didn't make my words accurate and clear enough. For example in my Assumption 4:

Old version: Initial kinetic energy and potential energy of target object are zero. 
Now after my modification: **Before** explosion, the kinetic energy and potential energy of target object are zero. object. An initial momentum will be assigned to each piece **when** explosion happens. 

So here I would like to assume that input target object cannot be a moving object. Perhaps my expression made it confused because I mention the initial momentum in GS. Actually they are in different time period. I should stressed the time period. So I believe in fact there is not conflict between this assumption and initial momentum.

As well as my data definition. I add decelerated motion in label. I do consider deceleration because of work done gravity force when pieces move in the air and work done by friction when pieces move on the ground.  I also modify assumption 2 to consider kinetic friction on the ground as constant force. So that particles do constant decelerated motion and will actually stop eventually.

I update a new version 4f530b7446a4c4a358272c683267e7c71f797573 with my modification and explanations like above. Hope those make my SRS clearer. 
Thank you for your review again ! :) @smiths 

Best Regards,
Marshall

**Comment by smiths** [comment]
Thank you for the clarification @MaXiaoye.  Your explanation that inaccurate English is part of the problem seems accurate to me.  I'm glad that you have already been able to fix some of the problems.  If at all possible, I encourage you to get a colleague to carefully review your SRS before the final submission.  I think you will be able to address my concerns and get a great grade on the final submission.

**Comment by MaXiaoye** [comment]
Updated in 4f530b7446a4c4a358272c683267e7c71f797573
