### ISSUE TITLE
Comments VnV  #1 - Gravity center calculation

### ISSUE THREAD

**Issue by slimpotatoes** [MaXiaoye/cas741#18]
Hi Xiaoye,

Please find below a few comments i have about your Test Plan. For your information, I am not familiar with unity3D so if my comments are not relevant with this aspect please do not consider them. I see that you interface with unity3D but i don't see what kind of information (input/output) is exchanged between your software and unity3D. This might be because of my lack of knowledge of what a game engine is :p.

My first comment is about the gravity center calculation. Initially I thought the gravity center was provided by unity3D but since you are testing it, it means you are calculating it.  However, I couldn't find any instance model calculating it. Since the calculation of the gravity center is a requirement (R4), I think you should have a module calculating it at some point in the SRS. Regarding the test, it is difficult to see what is precisely tested. Is a "piece" characterized by a 3D shape from which you take the center of gravity ? Depending on the shape, the gravity center calculation can be complicated (a project on its own :p). If you have any assumption on the shape (globe, parallelepiped, ...) it should be precised somewhere and also tested before calculating its center of gravity. Once the shape is defined, the calculation of the center of gravity can be simplified . You could even have in the SRS a Theoretical model of the center of gravity calculation (as a complete integral valid for any shape for example) and have an instance model that is the application of the general law on a specific geometry (for example, the center of mass is located at the center of the ball). 

To conclude, I think it's better to have a clear mathematical model of the gravity center calculation (even if the math is easy), to see exactly what is the calculation and what is precisely tested from the calculation.

**Comment by MaXiaoye** [comment]
Hi Alexandre,

Really appreciate for you detailed comments and review ! :)
Let me share more information here.
1. About “what kind of information (input/output) is exchanged between your software and unity3D”
Actually in unity3D, I consider each 3D-model is an object that can be controlled by its own script file. My codes are in the script file, so that I can attach it to any 3D object to simulate its explosion and breaking effect. Hope it is clear how my codes works with unity objects. :) 

2.About the gravity center.
Your initial thought is right :). The gravity center is provided by unity. Because I use cutting function in unity to split the target object. I don’t calculate the gravity center since after cutting, gravity centers of all pieces are certainly there. But I must write a module to get them, let’s say a traverse algorithm to cover all pieces and store them. Please notice each piece is also considered as an object in Unity. Sorry about my inaccurate word “calculation” here that it makes confusion. I will modify it to “obtain”. In my SRS R4, I use the word “get”, I will modify it to “obtain” as well to make it clearer. So the test case is used to test if I can obtain and store gravity centers of all pieces successfully. :)

Best Regards,
Marshall

**Comment by MaXiaoye** [comment]
The gravity center is provided by unity. Please refer to comments above
