### ISSUE TITLE
Comments VnV  #4 - Performance test

### ISSUE THREAD

**Issue by slimpotatoes** [MaXiaoye/cas741#21]
In your Test plan, the test "testPerformance" seems to test the behavior of the software with lots of "pieces". This looks like a stress test to me so I was expecting to see the number of particules in the input test. I can read that the developer has to judge the results of the test and has to"Adjust amount of pieces to see the performance that if program can run smoothly in huge amount of pieces". Is the "amount of pieces" a parameter that you can ask from unity3D ? Or is it a choice to make in your software to reduce the number of piece to be processed to calculate only the motion of the chosen pieces?

Another point, since your software is not displaying the motion to the user but it's unity3D (or something else) how do you know that your software is the problem if the explosion is not smoothly displayed? Maybe your calculations are fast enough and it is another software that is not performing properly with important amount of data. Isn't it better to measure the calculation time of your software instead of judging the quality of a smooth explosion ? The time to perform all the calculations for all the pieces will really measure the performance of your software only and you can dissociate from unity3D.  I could image that unity3D should have some requirements from your software in how fast the data needs to be provided in order to assure a smooth explosion display.

**Comment by MaXiaoye** [comment]
Yes the "amount of pieces" a parameter that I can ask from unity3D. However it is related to one input “explosion level” E. Actually E is used to decide how many pieces an object is splitting into and initial speed of piece after the “explosion” happens. As I said in previous issue, I rely on cutting function provided by unity so that I need to pass E to the cutting function or selecting different cutting functions depends on E. 

For another point, you may know now although the output is taken by unity but unity will display the motion to us. We just launch our simple “game” (that just containing an animation of an object exploding :p ) so of course we know if the explosion is not smoothly displayed. My poor laptop runs at almost full capacity to launch unity itself so I assume if I then launch a “game” in unity, it will not very smooth.. :)

**Comment by MaXiaoye** [comment]
Please refer to answer above
