### ISSUE TITLE
Comments VnV #5 - Comparison with professional plug-in

### ISSUE THREAD

**Issue by slimpotatoes** [MaXiaoye/cas741#22]
I like your idea to compare your results to some other softwares. A kind a black box test with same inputs and compare the outputs. 

My comment will be on the description of the test. In your test plan I can read: "This test case is designed to compare Breaking Effect with existing plug-inin Unity3D. Visualization is the most important point of the project so this section aims to test if Breaking Effect simulates the explosion vividly." I found the terminology vividly a little ambiguous because I don't know if you want to say realistic or smooth (or both :) ). I think it would be better to judge the accuracy of your software since I would assume you want to be realistic. If the reality is well model by the theory, you can try to measure your accuracy by comparing your results to theoretical models. 

In your case, I don't know if a global theoretical model exist but maybe some benchmark exists. What I am proposing might be too complicated for this project but maybe it exists somewhere in the gaming industry or the scientific community a reference that everyone try to fit to check the accuracy of their code regarding explosion. For example, the invert pendulum is one benchmark model that is used in robotics (nonlinear control theory). The point is to try the most possible objective reference to draw a good comparison. 

That's all for my comments :). At the exception of your "testAngles" test where you need to add the test of the calculation with the coordinate (0,0,0), your test plan is complete :).

Cheers

Alex

**Comment by MaXiaoye** [comment]
Thank you Alex, :)

Yeah I agree with you about reality. Since this is a project for scientific computing class not for a game or animation design class. I will measure my accuracy by comparing your results to theoretical models. Your  words about benchmark and invert pendulum seems hard for me at the moment because of my lack knowledge in such area :p. However I do will check the accuracy of my codes. 
And yes I need to add the test of the case that coordinate is (0,0,0).
Thank you for your great comments again !

Best Regards,
Marshall

**Comment by MaXiaoye** [comment]
Fix in 952bd56f7bde2c351f47c79cec18b6d3fafc3ccd
